#arjeta_de_prueba_aprobada="4051 8856 0044 6623"
name = "cotorro"
compatibility_date = "2025-08-01"
compatibility_flags = ["python_workers"]
main = "src/entry.py"
workers_dev = true
account_id = "cc28cf159fc984d8f45fd0f4864a8a28"

#esto funciona
[ai]
binding = "AI"

[observability.logs]
enabled = true

#[assets]
#directory='./public/assets'
#binding='ASSETS'


#[[ai_bindings]]
#name = "AI"
#service = "ai"

[[routes]]
pattern = "api.alectrico.cl"
custom_domain = true

[[routes]]
pattern = "repair.alectrico.cl"
custom_domain = true


[[routes]]
pattern = "www.alectrico.cl"
custom_domain = true



[env.production]
name = "cotorro"
kv_namespaces = [ { binding = "BUY_ORDER",  id = "7a20ea90007a4f99a6a02e864f358144" }, 
                  { binding = "FINANCIERO", id = "21111b7a045f4f8190416bbf08801cc6" },
                  { binding = "NOMINA",     id = 'e2688fc220714a60bd0aee142c341e28'},
                  { binding = "DICT",       id = '1fa2129e5a9c4151963563df0026a5f5'},
                  { binding = "STATUS",     id = '803319e9f7a54a7e9d55fcd1ebfa1322'},
                  { binding = "DIALOGO",    id = '7ff51d1ff6c14315b56fb315d4fc533e'}]


secrets_store_secrets = [
  { binding = "META", store_id= '8bd2531eeb4e4cd48560c6e0f45b8db4', secret_name = "USER_TOKEN" },
  { binding = "AI_GALLEGO_USER_TOKEN", store_id= '8bd2531eeb4e4cd48560c6e0f45b8db4', secret_name = "AI_GALLEGO_USER_TOKEN" }, 
  { binding = "AE_REPAIR_USER_TOKEN", store_id= '8bd2531eeb4e4cd48560c6e0f45b8db4', secret_name = "AE_REPAIR_USER_TOKEN" },
  { binding = "COTORRO_EXO_USER_TOKEN", store_id= '8bd2531eeb4e4cd48560c6e0f45b8db4', secret_name = "COTORRO_EXO_USER_TOKEN" },
  { binding = "AI_NUMBER_ID", store_id= '8bd2531eeb4e4cd48560c6e0f45b8db4', secret_name = "AI_NUMBER_ID" },
  { binding = "TOKEN_VENCIMIENTO", store_id= '8bd2531eeb4e4cd48560c6e0f45b8db4', secret_name = "TOKEN_VENCIMIENTO" },
  { binding = "I", store_id= '8bd2531eeb4e4cd48560c6e0f45b8db4', secret_name = "MODELO" },
  { binding = "INDUCCION_ALEXO", store_id= '8bd2531eeb4e4cd48560c6e0f45b8db4', secret_name = "INDUCCION_ALEXO" }

]


[[r2_buckets]]
binding='MEDIA'
bucket_name='assets'


#[ai_bindings]]
#ame = "AI"
#ervice = "ai"


[vars]

PRECIO_VISITA=68000
PRECIO_TOKEN=5000
PRECIO_PROCESO=1000

FONO_JEFE=56981370042
FONO_COLABORADOR=56981370042

ALEC_SEC_URL="https://wlhttp.sec.cl/rnii/public/licencia/qr?o=4b440313d7f8dfa0629155da8af59613"
VERIFY_TOKEN = "1"
GO_TBK_URL="https://www.alectrico.cl/transbank"


#-.................................. PRODUCTION -----------------------------------------
[env.production.vars]

#ASSETS EN BUCKET 'assets'
#accesible desde https://images.alectrico.cl/
API_URL = "https://images.alectrico.cl" 
LOGUITO_PATH='loguito.jpeg'
CONCURSO_PATH='logo_intendencia_sec.jpeg'
FIRST_TAKEME_IMAGE_PATH='tomar_lisa.png'
TAKEME_IMAGE_PATH='etherdog.png'
JEFE_IMAGE_PATH='alectricing.jpg'


WHATSAPP_BUSINESS_ACCOUNT_ID="107728605282500"
PHONE_NUMBER_ID="150477064807758"
VERIFY_TOKEN = "1"
SEGUNDOS_DE_EXPIRACION=6
NOMBRE_COLABORADOR="Juancho"
FONO_COLABORADOR=56981370042
FONO_JEFE=56981370042

ALEC_SEC_URL="https://wlhttp.sec.cl/rnii/public/licencia/qr?o=4b440313d7f8dfa0629155da8af59613"
PUBLICO_CLIENTE_HTML="932-000-849"
PUBLICO_COLABORADOR_HTML="932-000-849"
PUBLICO_CLIENTE="https://wa.me/+56932000849"
PUBLICO_COLABORADOR="https://wa.me/+56932000849"
ASSETS_SERVER_URL="https://alectrica.github.io/pay/assets"
TLD="alectrico"
MISION="Misión: Ayudar a progeter la vida y la propiedad"
VIDEO_URL="https://youtu.be/VRLOySZVRlM"
CLIENT_PHONE_NUMBER_ID="120509644476862"
PRECIO_VISITA=68000
PRECIO_TOKEN=3000
PRECIO_PROCESO=1000
RETURN_URL="https://www.alectrico.cl/return_url"
GO_TBK_URL="https://www.alectrico.cl/transbank"
WEBPAY_API_KEY="597036225750"
WEBPAY_SHARED_SECRET="2438ac00992d73fe1c3a0b501e8a90bb"
TBK_ENDPOINT="https://webpay3g.transbank.cl/rswebpaytransaction/api/webpay/v1.2/transactions"
#---------------------------------END PRODUCTION ---------------------------------------

[env.development.vars]
SEGUNDOS_DE_EXPIRACION=6
NOMBRE_COLABORADOR="Juancho"

FIRST_TAKEME_IMAGE_PATH='tomar_lisa.png'
TAKEME_IMAGE_PATH='etherdog.png'

JEFE_IMAGE_PATH='alectricing.jpg'

ALEC_SEC_URL="https://wlhttp.sec.cl/rnii/public/licencia/qr?o=4b440313d7f8dfa0629155da8af59613"

Tarjeta_de_prueba_aprobada="4051 8856 0044 6623"
FONO_JEFE=56981370042
FONO_COLABORADOR=56981370042

LOGUITO_PATH='loguito.jpeg'
CONCURSO_PATH='logo_intendencia_sec.jpeg'

PUBLICO_CLIENTE=56932000849
PUBLICO_CLIENTE_HTML="932-000-849"
PUBLICO_COLABORADOR_HTML="932-000-849"
PUBLICO_COLABORADOR=56932000849
API_URL = "https://www.alectrico.cl"
ASSETS_SERVER_URL="https://alectrica.github.io/pay/assets"
TLD="alectrico"
MISION="Misión: Ayudar a progeter la vida y la propiedad"
VIDEO_URL="https://youtu.be/VRLOySZVRlM"
META_USER_TOKEN="AAMOsdbL40gBPmYZBMxy2CuIR4htZBuLki1l8w92a6gZBtb1Veug1uSDn8ThRgeZAbkmZA4QCJfA62UChZBIQrF5ZC5JUHhtts8VwZBWaCtBePqISdR3GyX9es6WOF9Fs9YnkZCU2D13ja22jSj0SY7drNCs5b24EXXAWrExlvvOU7OasHp3KczAQSuVdMa7EuIcSrcSxfwJVn28F"
WHATSAPP_BUSINESS_ACCOUNT_ID="107728605282500"
PHONE_NUMBER_ID="150477064807758"

PRECIO_VISITA=68000
PRECIO_TOKEN=5000
PRECIO_PROCESO=1000


RETURN_URL="https://www.alectrico.cl/return_url"
GO_TBK_URL="https://www.alectrico.cl/transbank"
WEBPAY_API_KEY="597055555532"
WEBPAY_SHARED_SECRET="579B532A7440BB0C9079DED94D31EA1615BACEB56610332264630D42D0A36B1C"
TBK_ENDPOINT="https://webpay3gint.transbank.cl/rswebpaytransaction/api/webpay/v1.2/transactions"

